{% set version = "1.0.6" %}

package:
  name: leb128
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/leb128/leb128-{{ version }}.tar.gz
  sha256: d29e3c80743e910f1b5d57e3e05b5c83348115bad65086f4689c1946680e96cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - leb128
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mohanson/leb128
  summary: LEB128(Little Endian Base 128)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
